server.port={server.port}
spring.data.mongodb.uri={pring.data.mongodb.uri}

DAILY_REPORT_EMAIL={DAILY_REPORT_EMAIL}
GMAIL_USER={GMAIL_USER}       # <-- Your sender Gmail address
GMAIL_PASS={GMAIL_PASS}    # <-- Your Gmail App Password (see Step C)